<a href="https://colab.research.google.com/github/yshzjq/Step-2.Statistical_Thinking-Machine-Learning/blob/main/Step%202.%20%ED%86%B5%EA%B3%84%EC%A0%81%20%EC%82%AC%EA%B3%A0%EC%99%80%20%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%20%EC%9E%85%EB%AC%B8/2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 데이터 처리용
import pandas as pd
import numpy as np

# 시각화용
import matplotlib.pyplot as plt
import seaborn as sns

# 머신러닝 관련
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

In [3]:
# Heart Disease 데이터
url ="/content/Heart_Disease_Prediction.csv"

# CSV 파일 읽기
df = pd.read_csv(url)

df.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [4]:
# 데이터 기본 정보 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      270 non-null    int64
 1   Sex                      270 non-null    int64
 2   Chest pain type          270 non-null    int64
 3   BP                       270 non-null    int64
 4   Cholesterol              270 non-null    int64
 5   FBS over 120             270 non-null    int64
 6   EKG results              270 non-null    int64
 7   Max HR                   270 non-null    int64
 8   Exercise angina          270 non-null    int64
 9   ST depression            270 non-null    float64
 10  Slope of ST              270 non-null    int64
 11  Number of vessels fluro  270 non-null    int64
 12  Thallium                 270 non-null    int64
 13  Heart Disease            270 non-null    object
dtypes: float64(1), int64(12), object(1)
memory usage: 29.7+ KB

In [6]:
# 기초 통계 확인
df.describe()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.00000,270.000000,270.000000,270.000000
mean,54.433333,0.677778,3.174074,131.344444,249.659259,0.148148,1.022222,149.677778,0.329630,1.05000,1.585185,0.670370,4.696296
std,9.109067,0.468195,0.950090,17.861608,51.686237,0.355906,0.997891,23.165717,0.470952,1.14521,0.614390,0.943896,1.940659
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.00000,1.000000,0.000000,3.000000
25%,48.000000,0.000000,3.000000,120.000000,213.000000,0.000000,0.000000,133.000000,0.000000,0.00000,1.000000,0.000000,3.000000
50%,55.000000,1.000000,3.000000,130.000000,245.000000,0.000000,2.000000,153.500000,0.000000,0.80000,2.000000,0.000000,3.000000
75%,61.000000,1.000000,4.000000,140.000000,280.000000,0.000000,2.000000,166.000000,1.000000,1.60000,2.000000,1.000000,7.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.20000,3.000000,3.000000,7.000000

In [7]:
# 예측 대상 (심장질환 여부)
y = df['Heart Disease']

# 입력 변수 (target 제외)
X = df.drop(columns=['Heart Disease'])

In [8]:
# 데이터 분리 (8:2)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y# 클래스 비율 유지
)

In [9]:
# 로지스틱 회귀 모델 생성
model = LogisticRegression(
    max_iter=1000# 반복 횟수 충분히 설정
)

In [10]:
# 모델 학습
model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [11]:
# 클래스 예측
y_pred = model.predict(X_test)

# 확률 예측 (질환 있을 확률)
y_prob = model.predict_proba(X_test)

y_pred[:5], y_prob[:5]

(array(['Absence', 'Absence', 'Absence', 'Presence', 'Absence'],
       dtype=object),
 array([[0.96280417, 0.03719583],
        [0.85728073, 0.14271927],
        [0.94379872, 0.05620128],
        [0.08448241, 0.91551759],
        [0.68256232, 0.31743768]]))

In [12]:
# 정확도
acc = accuracy_score(y_test, y_pred)

# 정밀도, 재현율, F1-score의 경우 pos_label을 이용해서 어떤 class를 Positive로 정의할지 설정 가능
# 만약에 pos_label을 사용안하면 자동으로 target 값(0/1) 중에서 1을 Positive로 설정
# 하지만, 이 데이터에서는 target 값이 0,1로 되어있지 않기 때문에 pos_label로 직접 설정해줌

# 정밀도
prec = precision_score(y_test, y_pred, pos_label='Presence')

# 재현율
rec = recall_score(y_test, y_pred, pos_label='Presence')

# F1-score
f1 = f1_score(y_test, y_pred, pos_label='Presence')

acc, prec, rec, f1

(0.8518518518518519,
 0.7857142857142857,
 0.9166666666666666,
 0.8461538461538461)

In [14]:
# 종합 분류 성능 리포트
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

     Absence       0.92      0.80      0.86        30
    Presence       0.79      0.92      0.85        24

    accuracy                           0.85        54
   macro avg       0.85      0.86      0.85        54
weighted avg       0.86      0.85      0.85        54