<a href="https://colab.research.google.com/github/yshzjq/Step-2.Statistical_Thinking-Machine-Learning/blob/main/Step%202.%20%ED%86%B5%EA%B3%84%EC%A0%81%20%EC%82%AC%EA%B3%A0%EC%99%80%20%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%20%EC%9E%85%EB%AC%B8/2_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 데이터 처리용
import pandas as pd# 데이터프레임 처리
import numpy as np# 수치 계산

# 시각화용
import matplotlib.pyplot as plt# 그래프
import seaborn as sns# 예쁜 그래프

# 머신러닝 / 텍스트 처리
from sklearn.model_selection import train_test_split# 데이터 분리
from sklearn.feature_extraction.text import CountVectorizer# BoW
from sklearn.feature_extraction.text import TfidfVectorizer# TF-IDF
from sklearn.naive_bayes import MultinomialNB # 나이브 베이즈
from sklearn.metrics import classification_report# 평가 리포트

In [3]:
# SMS 스팸 데이터 URL (공용 미러)
url ="https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

# TSV 파일 읽기
df = pd.read_csv(url, sep='\t', header=None)

# 컬럼명 지정
df.columns = ['label','message']

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
# 'ham' → 0, 'spam' → 1로 변환
df['label_num'] = df['label'].map({'ham':0,'spam':1})

df.head()

  label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0

In [5]:
# 입력(X): 문자 메시지
X = df['message']

# 정답(y): 스팸 여부
y = df['label_num']

# 데이터 분리 (8:2)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y# 스팸/정상 비율 유지
)

In [6]:
# Bag of Words 벡터라이저 생성
bow = CountVectorizer()

# 학습 데이터 기준으로 단어 사전 생성 + 변환
X_train_bow = bow.fit_transform(X_train)

# 테스트 데이터 변환
X_test_bow = bow.transform(X_test)

bow.vocabulary_

{'he': 3373,
 'will': 7439,
 'you': 7629,
 'guys': 3290,
 'close': 1861,
 'can': 1646,
 'please': 5210,
 'come': 1919,
 'up': 7107,
 'now': 4812,
 'imin': 3629,
 'town': 6927,
 'dontmatter': 2420,
 'if': 3608,
 'urgoin': 7133,
 'outl8r': 4981,
 'just': 3873,
 'reallyneed': 5558,
 '2docd': 390,
 'dontplease': 2421,
 'dontignore': 2419,
 'mycalls': 4645,
 'no': 4770,
 'thecd': 6748,
 'isv': 3759,
 'important': 3637,
 'tome': 6881,
 '2moro': 403,
 'ok': 4889,
 'sry': 6376,
 'knw': 3962,
 'siva': 6148,
 'tats': 6648,
 'askd': 1104,
 'll': 4157,
 'see': 5933,
 'but': 1592,
 'prolly': 5403,
 'yeah': 7601,
 'swing': 6595,
 'by': 1607,
 'in': 3648,
 'bit': 1380,
 'got': 3209,
 'some': 6250,
 'things': 6775,
 'to': 6859,
 'take': 6621,
 'care': 1667,
 'of': 4864,
 'here': 3420,
 'firsg': 2887,
 'shall': 6011,
 'book': 1440,
 'chez': 1788,
 'jules': 3864,
 'for': 2951,
 'half': 3310,
 'eight': 2559,
 'that': 6739,
 'with': 7470,
 'thanks': 6733,
 'your': 7633,
 'message': 4444,
 'really': 5557,
 'appreciate': 1042,
 'sacrifice': 5822,
 'not': 4798,
 'sure': 6563,
 'the': 6743,
 'process': 5390,
 'direct': 2346,
 'pay': 5084,
 'find': 2869,
 'out': 4975,
 'on': 4908,
 'my': 4644,
 'way': 7331,
 'back': 1204,
 'from': 3032,
 'test': 6712,
 'tomorrow': 6885,
 'class': 1843,
 'do': 2382,
 'have': 3364,
 'wonderful': 7501,
 'day': 2192,
 'feb': 2813,
 'lt': 4244,
 'gt': 3269,
 'is': 3748,
 'love': 4222,
 'send': 5958,
 'dis': 2351,
 'all': 921,
 'ur': 7126,
 'valued': 7173,
 'frnds': 3025,
 'evn': 2697,
 'me': 4397,
 'comes': 1921,
 'married': 4353,
 'person': 5128,
 'luv': 4259,
 'ignore': 3612,
 'lose': 4202,
 'evr': 2700,
 'chinese': 1807,
 'food': 2943,
 'its': 3766,
 'when': 7403,
 'get': 3128,
 'fat': 2797,
 're': 5539,
 'paying': 5089,
 'lipo': 4136,
 'free': 2995,
 'nokia': 4778,
 'or': 4945,
 'motorola': 4580,
 'upto': 7124,
 '12mths': 289,
 '2price': 417,
 'linerental': 4125,
 '500': 547,
 'net': 4721,
 'mins': 4480,
 '100txt': 261,
 'mth': 4606,
 'tooth': 6903,
 'call': 1622,
 'mobileupd8': 4528,
 '08001950382': 50,
 '2optout': 415,
 'd3wv': 2153,
 'jus': 3872,
 'came': 1642,
 'fr': 2984,
 'lunch': 4255,
 'wif': 7430,
 'sis': 6137,
 'only': 4920,
 'leh': 4069,
 'yup': 7653,
 'elaborating': 2567,
 'safety': 5828,
 'aspects': 1112,
 'and': 974,
 'other': 4967,
 'issues': 3758,
 'lor': 4200,
 'anyway': 1017,
 'thk': 6785,
 'we': 7335,
 'cant': 1656,
 'tickets': 6818,
 'cos': 2028,
 'like': 4108,
 'quite': 5485,
 'late': 4022,
 'already': 934,
 'wan': 7294,
 'go': 3169,
 'look': 4190,
 'frens': 3007,
 'darren': 2180,
 'them': 6752,
 'helloooo': 3407,
 'wake': 7279,
 'sweet': 6587,
 'morning': 4569,
 'welcomes': 7374,
 'enjoy': 2613,
 'this': 6784,
 'full': 3050,
 'joy': 3853,
 'gud': 3275,
 'mrng': 4593,
 'pls': 5217,
 'da': 2154,
 'what': 7396,
 'happen': 3331,
 '09094100151': 242,
 'use': 7143,
 'calls': 1637,
 'cast': 1691,
 '10p': 266,
 'min': 4468,
 'mob': 4523,
 'vary': 7180,
 'service': 5981,
 'provided': 5425,
 'aom': 1020,
 'gbp5': 3106,
 'month': 4558,
 'box61': 1482,
 'm60': 4276,
 '1er': 332,
 'until': 7105,
 'stop': 6440,
 'ages': 878,
 '18': 322,
 'are': 1061,
 'awake': 1178,
 'there': 6761,
 'snow': 6231,
 'hmph': 3463,
 'head': 3374,
 'big': 1359,
 'baller': 1220,
 'gonna': 3191,
 'be': 1284,
 'at': 1123,
 'blake': 1392,
 'night': 4751,
 'might': 4460,
 'able': 763,
 'little': 4149,
 'early': 2514,
 'thanx': 6737,
 'lot': 4208,
 'oh': 4884,
 'ic': 3587,
 'thought': 6793,
 'meant': 4404,
 'mary': 4357,
 'jane': 3793,
 'tv': 7004,
 'watch': 7317,
 'meh': 4420,
 'work': 7514,
 'today': 6866,
 'want': 7298,
 'new': 4733,
 'video': 7205,
 'phone': 5152,
 '750': 627,
 'anytime': 1016,
 'any': 1008,
 'network': 4726,
 'price': 5359,
 'line': 4122,
 'rental': 5652,
 'text': 6715,
 'months': 4561,
 'reply': 5666,
 '08000930705': 48,
 'delivery': 2248,
 'notice': 4803,
 'looking': 4194,
 'shit': 6047,
 'mirror': 4487,
 'youre': 7634,
 'turning': 7002,
 'into': 3719,
 'right': 5730,
 'freak': 2992,
 'management': 4326,
 'puzzeles': 5466,
 'tension': 6699,
 'face': 2754,
 'smiling': 6209,
 'waste': 7313,
 'innocent': 3692,
 'terror': 6707,
 'cruel': 2097,
 'romantic': 5766,
 'lovable': 4221,
 'decent': 2212,
 'joker': 3840,
 'sunny': 6544,
 'california': 1621,
 'weather': 7343,
 'cool': 2014,
 'fyi': 3068,
 'usf': 7149,
 'room': 5768,
 'whenever': 7404,
 'asked': 1105,
 'sen': 5957,
 'chennai': 1781,
 'search': 5918,
 'job': 3829,
 'it': 3760,
 'flood': 2915,
 'pretty': 5354,
 'pussy': 5462,
 'cum': 2125,
 'going': 3181,
 'esplanade': 2662,
 'home': 3482,
 'an': 970,
 'customer': 2139,
 'announcement': 989,
 'freephone': 3002,
 '0800': 45,
 '542': 565,
 '0825': 59,
 'how': 3527,
 'wish': 7462,
 'great': 3242,
 'semester': 5955,
 'hi': 3431,
 'happy': 3340,
 'birthday': 1378,
 'opinion': 4935,
 'something': 6259,
 'first': 2888,
 'done': 2415,
 'internet': 3715,
 'connection': 1980,
 'slow': 6189,
 'try': 6980,
 'again': 869,
 'later': 4025,
 'thing': 6774,
 'tomo': 6883,
 'anything': 1015,
 'am': 946,
 'film': 2860,
 '2day': 389,
 '6pm': 616,
 'sorry': 6283,
 'put': 5463,
 'box': 1468,
 'dai': 2161,
 'resume': 5704,
 'id': 3595,
 'yes': 7612,
 'appt': 1050,
 'mean': 4400,
 'she': 6023,
 'told': 6875,
 'hr': 3538,
 'posting': 5294,
 'because': 1295,
 'working': 7518,
 'know': 3958,
 'why': 7424,
 'god': 3175,
 'created': 2077,
 'gap': 3086,
 'between': 1348,
 'fingers': 2874,
 'so': 6235,
 'one': 4914,
 'who': 7416,
 'made': 4296,
 'amp': 963,
 'fills': 2859,
 'those': 6791,
 'gaps': 3087,
 'holding': 3475,
 'hand': 3316,
 'slide': 6180,
 'enough': 2619,
 'bless': 1399,
 'good': 3193,
 'sleep': 6170,
 'dear': 2204,
 'pray': 5325,
 'called': 1629,
 'pick': 5163,
 'ask': 1103,
 'both': 1458,
 'they': 6769,
 'said': 5830,
 'finish': 2875,
 'mon': 4547,
 'thurs': 6812,
 'cash': 1687,
 'balance': 1218,
 'currently': 2134,
 'pounds': 5302,
 'maximize': 4387,
 '86688': 693,
 '150p': 306,
 'msg': 4596,
 'cc': 1707,
 '08718720201': 129,
 'hg': 3430,
 'suite342': 6529,
 '2lands': 401,
 'row': 5779,
 'w1j6hl': 7259,
 'babe': 1197,
 'dont': 2417,
 'baby': 1199,
 'im': 3624,
 'nasty': 4676,
 'filthyguys': 2863,
 'fancy': 2784,
 'rude': 5793,
 'time': 6827,
 'sexy': 5997,
 'bitch': 1381,
 'about': 765,
 'slo': 6185,
 'hard': 3341,
 'txt': 7015,
 'xxx': 7580,
 '4msgs': 532,
 'noe': 4773,
 'wat': 7316,
 'place': 5189,
 'dat': 2183,
 'sells': 5953,
 '4d': 526,
 'closes': 1865,
 'joys': 3854,
 'lifeis': 4098,
 'waking': 7280,
 'each': 2510,
 'daywith': 2194,
 'thoughts': 6794,
 'somewheresomeone': 6265,
 'cares': 1675,
 'tosend': 6914,
 'warm': 7305,
 'greeting': 3248,
 'juz': 3878,
 'remembered': 5637,
 'gotta': 3213,
 'bathe': 1260,
 'dog': 2396,
 'went': 7380,
 'project': 5402,
 'centre': 1723,
 'financial': 2868,
 'problem': 5383,
 'help': 3408,
 'gift': 3142,
 'yoyyooo': 7642,
 'change': 1737,
 'permissions': 5124,
 'drive': 2463,
 'mac': 4283,
 'usb': 7141,
 'flash': 2903,
 'watching': 7320,
 'house': 3522,
 'very': 7196,
 'entertaining': 2625,
 'getting': 3136,
 'whole': 7418,
 'hugh': 3548,
 'laurie': 4033,
 'even': 2677,
 'stick': 6426,
 'indeed': 3667,
 'especially': 2661,
 'explicit': 2736,
 'sex': 5994,
 '30': 432,
 'secs': 5929,
 'ring': 5735,
 '02073162414': 11,
 'costs': 2032,
 '20p': 358,
 'gsex': 3267,
 'pobox': 5226,
 '2667': 377,
 'wc1n': 7333,
 '3xx': 485,
 'borrow': 1454,
 'bag': 1209,
 'ringtone': 5738,
 '87131': 700,
 'poly': 5252,
 'true': 6973,
 'tone': 6887,
 '0845': 64,
 '2814032': 381,
 '16': 317,
 'after': 862,
 '1st': 339,
 'tones': 6888,
 '3x': 484,
 '150pw': 312,
 'nd': 4692,
 'hopefully': 3498,
 'den': 2253,
 'schedule': 5889,
 'lk': 4155,
 'sun': 6539,
 'uh': 7039,
 'heads': 3378,
 'don': 2413,
 'much': 4613,
 'left': 4064,
 'live': 4150,
 '121': 280,
 'chat': 1757,
 '60p': 584,
 'choose': 1817,
 'girl': 3149,
 'connect': 1978,
 '09094646899': 243,
 'cheap': 1762,
 'uk': 7043,
 'biggest': 1361,
 'vu': 7254,
 'bcm1896wc1n3xx': 1277,
 'sir': 6135,
 'waiting': 7278,
 'once': 4912,
 'planning': 5198,
 'usually': 7154,
 'stops': 6443,
 'hella': 3405,
 'weed': 7357,
 'smoke': 6211,
 'nt': 4818,
 'joking': 3843,
 'seriously': 5978,
 'ranjith': 5521,
 'cal': 1617,
 'drpd': 2473,
 'deeraj': 2227,
 'deepak': 2225,
 '5min': 570,
 'hold': 3473,
 'give': 3155,
 'walk': 7283,
 'was': 7310,
 'bathroom': 1262,
 'sup': 6550,
 'aiyar': 899,
 'type': 7029,
 'then': 6756,
 'tell': 6684,
 'scold': 5893,
 'takin': 6625,
 'linear': 4123,
 'algebra': 917,
 'private': 5373,
 '2003': 351,
 'account': 793,
 'statement': 6405,
 'shows': 6087,
 '800': 642,
 'un': 7052,
 'redeemed': 5598,
 'points': 5246,
 '08718738001': 142,
 'identifier': 3601,
 'code': 1892,
 '49557': 523,
 'expires': 2733,
 '26': 376,
 '11': 269,
 '04': 15,
 'lovly': 4234,
 'ho': 3466,
 'these': 6763,
 'words': 7513,
 'talking': 6632,
 'keeping': 3904,
 'away': 1181,
 'means': 4403,
 'still': 6429,
 'think': 6776,
 'teju': 6680,
 'cheers': 1775,
 'tex': 6714,
 'mecause': 4408,
 'werebored': 7383,
 'okden': 4892,
 'hunny': 3561,
 'uin': 7041,
 'wk': 7478,
 'sat': 5861,
 'sound': 6293,
 'likeyour': 4112,
 'havin': 3369,
 'gr8fun': 3221,
 'keep': 3903,
 'updat': 7111,
 'countinlots': 2041,
 'loveme': 4226,
 'xxxxx': 7583,
 'eat': 2525,
 'tonight': 6893,
 'purity': 5455,
 'friendship': 3019,
 'two': 7013,
 'reading': 5547,
 'forwarded': 2975,
 'seeing': 5935,
 'name': 4663,
 'evng': 2698,
 'shoot': 6060,
 'docs': 2388,
 'continued': 1999,
 'support': 6557,
 'question': 5478,
 'week': 7358,
 'enter': 2621,
 'in2': 3649,
 'our': 4972,
 'draw': 2450,
 '100': 255,
 'us': 7139,
 'president': 5346,
 'ans': 995,
 '80082': 646,
 '449071512431': 510,
 'urgent': 7129,
 '2nd': 411,
 'attempt': 1134,
 'contact': 1991,
 'won': 7497,
 '1250': 284,
 '09071512433': 239,
 'b4': 1189,
 '050703': 18,
 'csbcm4235wc1n3xx': 2104,
 'callcost': 1626,
 '150ppm': 310,
 'mobilesvary': 4527,
 'max': 4384,
 '50': 546,
 'fucking': 3043,
 'too': 6897,
 'fuck': 3040,
 'hear': 3385,
 'voice': 7242,
 'need': 4705,
 'crave': 2070,
 'adore': 832,
 'ahmad': 888,
 'kisses': 3945,
 'erm': 2646,
 'ill': 3620,
 '45pm': 515,
 'park': 5050,
 'dun': 2495,
 'sch': 5888,
 'beautiful': 1291,
 'truth': 6979,
 'against': 870,
 'gravity': 3239,
 'read': 5545,
 'carefully': 1673,
 'heart': 3389,
 'feels': 2823,
 'light': 4104,
 'someone': 6254,
 'heavy': 3396,
 'leaves': 4059,
 'goodmorning': 3197,
 '000': 1,
 'prize': 5376,
 'claim': 1835,
 'call09050000327': 1623,
 'rstm': 5786,
 'sw7': 6577,
 '3ss': 481,
 'wil': 7436,
 'horrible': 3507,
 'gal': 3076,
 'knew': 3954,
 'him': 3441,
 'yest': 7613,
 'as': 1094,
 'sim': 6118,
 'subscriber': 6503,
 'selected': 5945,
 'receive': 5575,
 'bonus': 1437,
 'delivered': 2246,
 'door': 2424,
 'word': 7512,
 '88600': 710,
 'exp': 2722,
 '30apr': 439,
 'shower': 6082,
 'hey': 3428,
 'fri': 3011,
 'miwa': 4506,
 'jiayin': 3823,
 'leave': 4058,
 'karaoke': 3894,
 'ex': 2703,
 'wife': 7431,
 'kids': 3928,
 'wamma': 7293,
 'laid': 3996,
 'real': 5549,
 'doggin': 2399,
 'locations': 4169,
 'sent': 5968,
 'mobile': 4524,
 'join': 3836,
 'uks': 7045,
 'largest': 4018,
 'dogging': 2400,
 'dogs': 2402,
 '69696': 603,
 'nyt': 4843,
 'ec2a': 2530,
 '3lp': 473,
 'nothing': 4802,
 'money': 4550,
 'enters': 2623,
 'bank': 1230,
 'remove': 5646,
 'flat': 2904,
 'rate': 5524,
 'transfered': 6945,
 'dollars': 2410,
 'removed': 5647,
 'banks': 1231,
 'differ': 2321,
 'charges': 1748,
 'also': 937,
 'trust': 6978,
 '9ja': 743,
 'sending': 5960,
 'details': 2285,
 'missing': 4495,
 'sender': 5959,
 'number': 4826,
 'date': 2184,
 'thats': 6742,
 'everything': 2692,
 'via': 7198,
 'fullonsms': 3051,
 'com': 1914,
 'prof': 5394,
 'passed': 5066,
 'papers': 5037,
 'sem': 5954,
 'congrats': 1975,
 'student': 6475,
 'enna': 2618,
 'kalaachutaarama': 3886,
 'ah': 883,
 'plus': 5219,
 'workin': 7517,
 'oso': 4966,
 'rite': 5747,
 'orchard': 4951,
 'liao': 4088,
 'yay': 7600,
 'finally': 2866,
 'lol': 4180,
 'missed': 4493,
 'cinema': 1830,
 'trip': 6964,
 'last': 4020,
 'kallis': 3889,
 'ground': 3259,
 'amla': 954,
 'durban': 2499,
 'havent': 3367,
 'probably': 5382,
 'pop': 5268,
 'weekend': 7360,
 'did': 2312,
 'miss': 4492,
 'worry': 7525,
 'guess': 3278,
 'busy': 1591,
 'sentence': 5969,
 'concentrate': 1957,
 'educational': 2540,
 'career': 1670,
 'leaving': 4060,
 'kano': 3892,
 'whr': 7423,
 'treat': 6958,
 'maga': 4300,
 'trouble': 6970,
 'buy': 1596,
 'dad': 2158,
 '1405': 296,
 '1680': 319,
 '1843': 324,
 'small': 6196,
 'order': 4952,
 'reference': 5602,
 'x29': 7567,
 'charged': 1747,
 'should': 6074,
 'arrive': 1084,
 'services': 5982,
 '09065989180': 220,
 '07734396839': 28,
 'ibh': 3580,
 'loyalty': 4240,
 'offer': 4871,
 'nokia6600': 4779,
 '10': 254,
 'txtauction': 7019,
 'start': 6397,
 '81151': 657,
 'yours': 7636,
 '4t': 535,
 'tht': 6809,
 'incident': 3653,
 'flippin': 2911,
 'yet': 7615,
 'paper': 5036,
 'princess': 5364,
 'every': 2684,
 'command': 1926,
 'were': 7382,
 'thinking': 6779,
 'staying': 6412,
 'mcr': 4396,
 'had': 3300,
 'contract': 2000,
 'mnths': 4520,
 'latest': 4026,
 'etc': 2666,
 'double': 2432,
 'orange': 4948,
 'tariffs': 6642,
 'callback': 1625,
 'records': 5590,
 'excellent': 2708,
 'together': 6870,
 'pleased': 5211,
 'advise': 845,
 'following': 2938,
 'recent': 5579,
 'review': 5718,
 'awarded': 1180,
 '1500': 305,
 '09066364589': 229,
 'almost': 930,
 'forgot': 2962,
 'ya': 7589,
 'ard': 1060,
 'reach': 5540,
 'sometimes': 6261,
 'walls': 7290,
 'around': 1080,
 'hearts': 3391,
 'safe': 5826,
 'hurt': 3566,
 'break': 1505,
 'closer': 1864,
 'goodnoon': 3200,
 'remember': 5636,
 'old': 4901,
 'commercial': 1928,
 'shopping': 6063,
 'present': 5345,
 'started': 6398,
 'guessing': 3281,
 'guessed': 3279,
 'decide': 2213,
 'vikky': 7214,
 'olave': 4900,
 'mandara': 4330,
 'movie': 4586,
 'trishul': 6967,
 'theatre': 6747,
 'wit': 7469,
 'her': 3419,
 'stay': 6409,
 'been': 1307,
 'tough': 6923,
 'optimistic': 4941,
 'improve': 3645,
 'dude': 2487,
 'buff': 1565,
 'wind': 7444,
 'year': 7602,
 'alright': 935,
 'advice': 844,
 'ma': 4280,
 'showing': 6085,
 'cld': 1846,
 'drink': 2458,
 'before': 1312,
 'wld': 7485,
 'prefer': 5333,
 'spend': 6328,
 'nosh': 4797,
 'mind': 4470,
 'doing': 2405,
 'nxt': 4839,
 'sef': 5941,
 'dey': 2297,
 'laugh': 4029,
 'meanwhile': 4405,
 'darling': 2178,
 'anjie': 983,
 'sooooo': 6279,
 'bed': 1301,
 'lonely': 4185,
 'dream': 2452,
 'smsing': 6219,
 'xy': 7587,
 'neva': 4729,
 'sort': 6284,
 'meet': 4413,
 'bring': 1525,
 'along': 932,
 'next': 4742,
 'meeting': 4415,
 'well': 7375,
 'confuses': 1974,
 'doesn': 2394,
 'kate': 3896,
 'asap': 1096,
 'run': 5804,
 'frm': 3022,
 'slowly': 6192,
 'kills': 3934,
 'convey': 2006,
 'regards': 5616,
 'wouldn': 7537,
 'hour': 3519,
 'least': 4057,
 'ujhhhhhhh': 7042,
 'computer': 1953,
 'shipped': 6043,
 'address': 823,
 'sandiago': 5845,
 'parantella': 5043,
 'lane': 4007,
 'wtf': 7556,
 'poop': 5264,
 'toledo': 6876,
 'say': 5878,
 'clean': 1847,
 'blood': 1413,
 'ten': 6695,
 'special': 6316,
 'people': 5109,
 'miracle': 4486,
 'oredi': 4956,
 'telugu': 6690,
 'abt': 772,
 'hello': 3406,
 'handsome': 3322,
 'finding': 2870,
 'being': 1323,
 'lazy': 4042,
 'towards': 6926,
 'mummy': 4625,
 'where': 7406,
 'boytoy': 1490,
 'does': 2392,
 'elaine': 2568,
 'evening': 2678,
 'hope': 3495,
 'having': 3370,
 'nice': 4746,
 'wanted': 7300,
 'rent': 5651,
 'past': 5071,
 'few': 2834,
 'charge': 1746,
 'felt': 2828,
 'would': 7535,
 'inconsiderate': 3660,
 'nag': 4656,
 'cost': 2029,
 'yourself': 7637,
 'didnt': 2315,
 'speak': 6314,
 'however': 3531,
 'recession': 5582,
 'wont': 7504,
 'hence': 3416,
 'askin': 1106,
 'ahead': 885,
 'end': 2597,
 'thank': 6732,
 'download': 2437,
 'fring': 3021,
 'app': 1030,
 'yar': 7594,
 'raining': 5502,
 'non': 4782,
 'elsewhere': 2579,
 'total': 6918,
 'disappointment': 2353,
 'texted': 6721,
 'craziest': 2072,
 'city': 1832,
 'could': 2037,
 'win': 7442,
 '200': 349,
 'summer': 6535,
 'spree': 6364,
 'store': 6446,
 '88039': 706,
 'skilgme': 6154,
 'tscs087147403231winawk': 6986,
 'age16': 873,
 '50perwksub': 553,
 'battery': 1265,
 'died': 2317,
 'gram': 3226,
 ...}

In [7]:
bow.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [8]:
bow_df = pd.DataFrame(
    X_train_bow.toarray(),
    columns=bow.get_feature_names_out()
)

bow_df.head()

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,02,0207,...,zed,zeros,zhong,zindgi,zoe,zogtorius,zyada,èn,ú1,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
row0 = bow_df.iloc[1]

# 값이 0이 아닌 컬럼 위치
col_positions = row0[row0 > 0].index
col_positions

Index(['2docd', '2moro', 'can', 'come', 'dontignore', 'dontmatter',
       'dontplease', 'if', 'imin', 'important', 'isv', 'just', 'mycalls', 'no',
       'now', 'outl8r', 'please', 'reallyneed', 'thecd', 'tome', 'town', 'up',
       'urgoin'],
      dtype='object')

In [10]:
print(df.shape)

print(df.tail())

(5572, 3)
     label                                            message  label_num
5567  spam  This is the 2nd time we have tried 2 contact u...          1
5568   ham               Will ü b going to esplanade fr home?          0
5569   ham  Pity, * was in mood for that. So...any other s...          0
5570   ham  The guy did some bitching but I acted like i'd...          0
5571   ham                         Rofl. Its true to its name          0

In [13]:
# 나이브 베이즈 모델 생성
nb_bow = MultinomialNB()

# 모델 학습
nb_bow.fit(X_train_bow, y_train)

MultinomialNB()

In [14]:
# 예측 수행
y_pred_bow = nb_bow.predict(X_test_bow)

# 분류 성능 출력
print("Bag of Words 결과")
print(classification_report(y_test, y_pred_bow))

Bag of Words 결과
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       966
           1       0.99      0.92      0.95       149

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [15]:
# TF-IDF 벡터라이저 생성
tfidf = TfidfVectorizer()

# 학습 데이터 변환
X_train_tfidf = tfidf.fit_transform(X_train)

# 테스트 데이터 변환
X_test_tfidf = tfidf.transform(X_test)

In [20]:
tfidf.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [21]:
tfidf_df = pd.DataFrame(
    X_train_tfidf.toarray(),
    columns=tfidf.get_feature_names_out()
)

tfidf_df.head()

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,02,0207,...,zed,zeros,zhong,zindgi,zoe,zogtorius,zyada,èn,ú1,〨ud
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
row0 = tfidf_df.iloc[1]

# 값이 정확히 1인 컬럼 위치 (정수 인덱스)
col_positions = row0[row0 > 0].index
col_positions

Index(['2docd', '2moro', 'can', 'come', 'dontignore', 'dontmatter',
       'dontplease', 'if', 'imin', 'important', 'isv', 'just', 'mycalls', 'no',
       'now', 'outl8r', 'please', 'reallyneed', 'thecd', 'tome', 'town', 'up',
       'urgoin'],
      dtype='object')

In [23]:
# 나이브 베이즈 모델 생성
nb_tfidf = MultinomialNB()

# 모델 학습
nb_tfidf.fit(X_train_tfidf, y_train)

MultinomialNB()

In [24]:
# 예측 수행
y_pred_tfidf = nb_tfidf.predict(X_test_tfidf)

# 분류 성능 출력
print("TF-IDF 결과")
print(classification_report(y_test, y_pred_tfidf))

TF-IDF 결과
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       966
           1       1.00      0.70      0.83       149

    accuracy                           0.96      1115
   macro avg       0.98      0.85      0.90      1115
weighted avg       0.96      0.96      0.96      1115

In [25]:
# 테스트 데이터의 스팸 확률 예측
spam_prob_bow = nb_bow.predict_proba(X_test_bow)

spam_prob_bow[:10]

array([[9.99995084e-01, 4.91581714e-06],
       [1.00000000e+00, 8.45581173e-17],
       [1.00000000e+00, 1.16633731e-10],
       [6.48593235e-11, 1.00000000e+00],
       [9.99989877e-01, 1.01226136e-05],
       [1.00000000e+00, 9.38066487e-17],
       [9.99999814e-01, 1.85659269e-07],
       [9.99999951e-01, 4.85891046e-08],
       [1.00000000e+00, 6.97120532e-24],
       [9.99999995e-01, 4.66633182e-09]])

In [26]:
# 테스트 데이터의 스팸 확률 예측
spam_prob_tfidf = nb_tfidf.predict_proba(X_test_tfidf)

spam_prob_tfidf[:10]

array([[9.97627805e-01, 2.37219550e-03],
       [9.99878815e-01, 1.21185248e-04],
       [9.99198236e-01, 8.01764388e-04],
       [7.86434728e-02, 9.21356527e-01],
       [9.94893289e-01, 5.10671079e-03],
       [9.99104766e-01, 8.95233618e-04],
       [9.96308304e-01, 3.69169574e-03],
       [9.96064699e-01, 3.93530124e-03],
       [9.99892705e-01, 1.07294709e-04],
       [9.94842247e-01, 5.15775297e-03]])